#include "common.h"

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/func_80800000_chmumboskullfakearchpanellava.s")

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/func_80800054_chmumboskullfakearchpanellava.s")

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/func_8080008C_chmumboskullfakearchpanellava.s")

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava_entrypoint_0.s")

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/func_8080012C_chmumboskullfakearchpanellava.s")

#pragma GLOBAL_ASM("asm/nonmatchings/overlays/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava/chmumboskullfakearchpanellava_entrypoint_1.s")
