#ifndef __ASSETS_H__
#define __ASSETS_H__

typedef enum asset_e {
    ASSET_6_ANIM_BSLEDGE_UNKNOWN = 0x6,
    
    ASSET_D_ANIM_BSLEDGE_UNKNOWN = 0xD,

    ASSET_12_ANIM_BSLEDGE_UNKNOWN = 0x12,
    ASSET_13_ANIM_BSLEDGE_UNKNOWN,

    ASSET_17_ANIM_BSBFLAP = 0x17,
    ASSET_18_ANIM_BSBFLAP_ENTER = 0x18,

    ASSET_1C_ANIM_BSBBARGE = 0x1C,
    ASSET_1D_ANIM_BSBBUSTER,
    ASSET_1E_ANIM_BSLEDGE_UNKNOWN,

    ASSET_2A_ANIM_BSEGGHEAD = 0x2A,
    ASSET_2B_ANIM_BSEGGASS = 0x2B,

    ASSET_4B_ANIM_BSBFLIP_ENTER = 0x4B,
    ASSET_4C_ANIM_BSBFLIP_HOLD,
    ASSET_4D_ANIM_BSOW_UNKNOWN, // might not be an anim

    ASSET_4F_ANIM_BSTWIRL = 0x4F,
    ASSET_50_ANIM_BSREST_UNKNOWN,
    ASSET_51_ANIM_BSLEDGE_UNKNOWN,

    ASSET_5B_ANIM_BSREST_UNKNOWN = 0x5B,

    ASSET_9C_ANIM_BSMUMSWIM_UNKNOWN = 0x9C,
    ASSET_9D_ANIM_BSMUMSWIM_UNKNOWN,

    ASSET_A4_ANIM_BSKAZSHOESSUCKSPLINE = 0xA4,
    
    ASSET_A6_ANIM_BSKAZMOVE_UNKNOWN = 0xA6,
    ASSET_A7_ANIM_BSKAZMOVE_UNKNOWN,
    ASSET_A8_ANIM_BSKAZCROUCH_UNKNOWN,
    ASSET_A9_ANIM_BSKAZJUMP_UNKNOWN,
    ASSET_AA_ANIM_BZKAZFLY_UNKNOWN,
    ASSET_AB_ANIM_BZKAZFLY_UNKNOWN,

    ASSET_B3_ANIM_BSMUMMOVE_UNKNOWN = 0xB3,
    ASSET_B4_ANIM_BSMUMMOVE_UNKNOWN,

    ASSET_B8_ANIM_BSMUM_UNKNOWN = 0xB8,
    
    ASSET_BB_ANIM_BSMUM_UNKNOWN = 0xBB,

    ASSET_BD_BSMUM_ANIM_UNKNOWN = 0xBD,

    ASSET_CA_ANIM_BZKAZDIE_UNKNOWN = 0xCA,
    ASSET_CB_ANIM_BSMUMSPLAT_UNKNOWN,

    ASSET_11E_ANIM_BSKAZFLY_UNKNOWN = 0x11E,
    
    ASSET_137_ANIM_BSKAZWINGWHACK_UNKNOWN = 0x137,

    ASSET_139_ANIM_BSKAZPADDLE_UNKNOWN = 0x139,
    ASSET_13A_ANIM_BSKAZPADDLE_UNKNOWN,

    ASSET_13D_ANIM_KAZGLIDE_UNKNOWN = 0x13D,

    ASSET_13F_ANIM_KAZHATCH_UNKNOWN = 0x13F,
    ASSET_140_ANIM_KAZHATCH_UNKNOWN,
    ASSET_141_ANIM_BSKAZCROUCH_UNKNOWN,
    ASSET_142_ANIM_BSKAZSPRING_UNKNOWN,

    ASSET_149_ABIM_BSKAZSTILT_UNKNOWN = 0x149,
    ASSET_14A_ANIM_BSKAZSTILT_UNKNOWN,

    ASSET_24C_ANIM_BSKAZSHOESSPRINGJUMP_UNKNOWN = 0x24C,
    ASSET_24D_ANIM_BSKAZMOVE_UNKNOWN,

    ASSET_24F_ANIM_BSKAZMOVE_UNKNOWN = 0x24F,

    ASSET_27A_ANIM_BSKAZSHOCK_UNKNOWN = 0x27A,
    ASSET_27B_ANIM_BANBFLIP,
    ASSET_27C_ANIM_BSKAZSHOCK_UNKNOWN,

    ASSET_27F_ANIM_BSKAZSTILT_UNKNOWN = 0x27F,

    ASSET_288_ANIM_BSKAZFLY_UNKNOWN = 0x288,

    ASSET_28E_ANIM_BZKAZEGGASS_UNKNOWN = 0x28E,
    ASSET_28F_ANIM_BSKAZCROUCH_UNKNOWN,

    ASSET_29D_ANIM_BSKAZFLY_UNKNOWN = 0x29D,
    ASSET_29E_ANIM_BSKAZFLY_UNKNOWN,
    BLUE_SPARKLE = 0x9E0,
    GREEN_SPARKLE = 0x9E1,
    GOLD_SPARKLE = 0x9E2,
    ORANGE_SPARKLE = 0x9E3,
    RED_SPARKLE = 0x9E4,
    LIGHT_BLUE_SPARKLE = 0x9E5
} AssetId;

#endif
