#ifndef __TRANSFORMATIONS_H__
#define __TRANSFORMATIONS_H__

typedef enum transform_e {
	TRANSFORM_13_TREXLARGE = 0x13,
	TRANSFORM_12_TREXSMALL = 0x12,
	TRANSFORM_11_CLOCKWORK = 0x11,
	TRANSFORM_10_VAN = 0x10,
	TRANSFORM_F_DETONATOR = 0xF,
	TRANSFORM_E_GOLDENGOLIATH = 0xE,
	TRANSFORM_D_MUMBO = 0xD,
	TRANSFORM_C_SUB = 0xC,
	TRANSFORM_B_KAZOOIE = 0xB,
	TRANSFORM_A_BANJO = 0xA,
	TRANSFORM_9_FIRSTPERSON = 0x9,
	TRANSFORM_8_STONY = 0x8,
	TRANSFORM_7_WASHINGMACHINE = 0x7,
	TRANSFORM_6_BEE = 0x6,
	TRANSFORM_2_SNOWBALL = 0x2,
	TRANSFORM_1_BK = 0x1
} TransformationId;

#endif