#ifndef __ASSETS_H__
#define __ASSETS_H__

typedef enum asset_e {
    ASSET_17_ANIM_BSBFLAP = 0x17,
    ASSET_18_ANIM_BSBFLAP_ENTER = 0x18,

    ASSET_1C_ANIM_BSBBARGE = 0x1C,
    ASSET_1D_ANIM_BSBBUSTER,

    ASSET_2A_ANIM_BSEGGHEAD = 0x2A,
    ASSET_2B_ANIM_BSEGGASS = 0x2B,
    ASSET_4F_ANIM_BSTWIRL = 0x4F
} AssetId;

#endif
