#ifndef __ASSETS_H__
#define __ASSETS_H__

typedef enum asset_e {
    ASSET_17_ANIM_BSBFLAP = 0x17,
    ASSET_18_ANIM_BSBFLAP_ENTER = 0x18,

    ASSET_1C_ANIM_BSBBARGE = 0x1C,
    ASSET_1D_ANIM_BSBBUSTER,

    ASSET_2A_ANIM_BSEGGHEAD = 0x2A,
    ASSET_2B_ANIM_BSEGGASS = 0x2B,

    ASSET_4B_ANIM_BSBFLIP_ENTER = 0x4B,
    ASSET_4C_ANIM_BSBFLIP_HOLD = 0x4C,

    ASSET_4F_ANIM_BSTWIRL = 0x4F,

    ASSET_A8_ANIM_BSKAZCROUCH_UNKNOWN = 0xA8,

    ASSET_AA_ANIM_BZKAZFLY_UNKNOWN = 0xAA,
    ASSET_AB_ANIM_BZKAZFLY_UNKNOWN,

    ASSET_CA_ANIM_BZKAZDIE_UNKNOWN = 0xCA,

    ASSET_11E_ANIM_BSKAZFLY_UNKNOWN = 0x11E,
    
    ASSET_13D_ANIM_KAZGLIDE_UNKNOWN = 0x13D,

    ASSET_13F_ANIM_KAZHATCH_UNKNOWN = 0x13F,
    ASSET_140_ANIM_KAZHATCH_UNKNOWN,
    ASSET_141_ANIM_BSKAZCROUCH_UNKNOWN,

    ASSET_27B_ANIM_BANBFLIP = 0x27B,

    ASSET_288_ANIM_BSKAZFLY_UNKNOWN = 0x288,

    ASSET_28E_ANIM_BZKAZEGGASS_UNKNOWN = 0x28E,
    ASSET_28F_ANIM_BSKAZCROUCH_UNKNOWN,

    ASSET_29D_ANIM_BSKAZFLY_UNKNOWN = 0x29D,
    ASSET_29E_ANIM_BSKAZFLY_UNKNOWN
} AssetId;

#endif
